server:
  port: 8791

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/

spring:
  application:
    name: feign

# D版本后的spring cloud中feign集成了hystrix断路器，所以就不再新建工程了
# 设置hystrix打开。
feign:
  hystrix:
    enabled: true