spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          searchPaths: config
          username:
          password:

server:
  port: 8794
  servlet:
    contextPath: /config/server