server:
  port: 8797

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          # 并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router
          # 这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    # tmd不知道为啥service-url不行...
    serviceUrl:
      defaultZone: http://localhost:8787/eureka