## fescar 有3个基本组件
# TC 事务协调员
# TM 定义全局事务的范围
# RM 管理分支事务处理的资源，与TC通信以注册分支事务和报告分支事务的状态，并驱动分支事务提交或回滚

## fescar 的生命周期
# TM要求TC开启新的全局事务
# XID通过微服务的调用链传播
# RM将本地事务注册为XID到TC的相应全局事务的分支
# TM要求TC提交或回滚XID的相应全局事务
# TC在XID的相应全副事务下驱动所有的分支事务已完成分支提交或rollback。